name: Bug Report
description: For reporting bugs with the docs.
labels: [Bug]
body:
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Please specify the browser you're using.
      placeholder: "e.g. Chrome, Firefox, Safari"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: Please specify the device you are using.
      placeholder: "e.g. Phone, Tablet, Laptop, Desktop"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug you've encountered. What happened, and what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can drag and drop images here.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
